name: "DOCKER_PROJECT_NAME"

services:
  DOCKER_DB_NAME_wp_test_mariadb:
    #image: mysql:8.0.29
    image: mariadb:latest
    user: mysql
    ports:
      - 'DOCKER_DB_PORT:3306'
    volumes:
      - DOCKER_DB_VOLUME_NAME:/var/lib/mysql/
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp_test
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp

volumes:
  DOCKER_DB_VOLUME_NAME:
    driver_opts:
      type: tmpfs
      device: tmpfs
